# Math

In [10]:
print( "Hello world!" )

Hello world!


In [11]:
print( 1 + 2)

3


In [12]:
print( 1 - 5)

-4


In [13]:
print( 4 * 5 )
print( 4 / 5 )
print ( 3 ** 2 )
print ( 25 ** 0.5 )

20
0.8
9
5.0


### Order of operations

In [14]:
print( 1 + 2 * 3)
print(1 + (2 * 3))
print( (1 + 2) * 3)

7
7
9


### Veriables

A variable is a symbol that contains data.

In [8]:
x = 1
y = 10
z = 10001
print(x)
print(y)
print(z)

1
10
10001


In [9]:
print(x,y,z)

1 10 10001


In [17]:
print(x + y)
a = x + y
print(a)

11
11


### Dynamic typing ( type of variable)

In [19]:
x = 2
print(x, type(x))

x = 2.7
print(x, type(x))

x= "Hello!"
print(x, type(x))

2 <class 'int'>
2.7 <class 'float'>
Hello! <class 'str'>


### Variable names

- contain only lower-case letters (abcde... NOT ABCDE...) case-sensitive
- multi-name variables should be separated with underscores `_`

In [25]:
x0 = 1
x1 = 10
x2 = 200
print(x0, x1, x2)

1 10 200


In [26]:
0x = 100

SyntaxError: invalid hexadecimal literal (1198918811.py, line 1)

In [ ]:
a = 1
x = 10
ABC = 100 # not an error, but not Python convention

print(ABC)

my_favorite_ice_cream = 10

print( my_favorite_ice_cream )

100
10


# Lists and tuples

A list contains multiple variabls in a sequence

A tuple is a list cannot be changed

In [30]:
x = [0,5,8]
y = (0,5,8)

print(x)
print(type(x))

print(y)
print(type(y))

[0, 5, 8]
<class 'list'>
(0, 5, 8)
<class 'tuple'>


In [ ]:
x = [0,5,8]

print(x[0]) # first element of x; "zero indexing"
print(x[1]) # second
print(x[2]) # third

0
5
8


In [32]:
print(x[3})

SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' (3294411511.py, line 1)

In [35]:
print(x[-1]) # last element
print(x[-2]) # second last element
print(x[-3]) # third last element

8
5
0


In [36]:
print(x[-4])

IndexError: list index out of range

In [37]:
x = [0,10,100]
x[0] = 2000

print(x)

[2000, 10, 100]


In [38]:
x = (0,10,100)
print(x[0])

0


In [39]:
print(x(0))

TypeError: 'tuple' object is not callable

In [41]:
x = (0,10,100)
x[0] = 100

TypeError: 'tuple' object does not support item assignment

In [ ]:
g = (0,0,-9.812) #gravity vector does not change, so use a tuple

# Arrays

Creating arrays is usually done in Python using the Numpy package

Numpy: Numerical Python

- A package is like a library, containing several programming tools like functions and variables
- Package must be accessed using the "import" command in Python

In [1]:
import numpy
x = numpy.array( [0,5,8])

print(x, type(x)) # n-dimensional array

[0 5 8] <class 'numpy.ndarray'>


In [2]:
print(x[0])
print(x[1])

0
5


In [3]:
print(x+1)

[1 6 9]


In [4]:
a = [0,5,8]
print(a+1)

TypeError: can only concatenate list (not "int") to list

In [5]:
import numpy as np

a = np.array([0,1,5])
b = np.array([10,10,0])

print(a + b)


[10 11  5]


In [6]:
c = [0,1,5]
d = [10,10,0]

print(c + d)


[0, 1, 5, 10, 10, 0]


# Functions

A function accepts input variable (called "input argumants"), performs calculations, and then returns output variables (called "output arguments") to the caller.

In [7]:
def my_function(x):
    y = x + 1
    return y

print ( my_function(10))

11


- `def` : define function
- `my_function` : is the function name (should be named like variable names by convention)
- `x` : input argument
- `y` : output argument
- `return` : indicates that the function is finished

In [8]:
def my_function(x,y):
    z = x + y
    q = 100
    return y,q

a,b = my_function(1,2)
print(a,b)

2 100
